# 웹 서버 설정
server.port=8080

# Ollama AI 서버 설정
ollama.base.url=http://100.74.51.50:11434
ollama.embedding.model=bge-m3
ollama.chat.model=gemma4:latest

# RAG 시스템 데이터 저장소 경로 (이전에 얘기했던 JSON 파일)
rag.store.path=data/rag-store.json

crawler.cache.dir=data/parsingMD

# 학습할 데이터 
ingestion.urls=https://swcc.deu.ac.kr/se/index.do, \
               https://swcc.deu.ac.kr/se/sub02.do, \
               https://compnet.deu.ac.kr
ingestion.directory=data/docs